# PiWD - PS2

Cel zajęć: zapoznanie się z grupowaniem danych w pandas

Do demonstracji wykorzystamy zbiór danych _graduation_rate_ zamieszczony na CEZ. Pliki danych muszą być umieszczone w tym samym folderze co notatnik.

Natomiast zadania samodzielne będziecie Państwo wykonywać na zbiorze danych _heart_disease.csv_ . W dalszej cześci notatnika będzie on objaśniony

## Przykłady

In [59]:
import pandas as pd
df = pd.read_csv("graduation_rate.csv")
df

,ACT composite score,SAT total score,parental level of education,parental income,high school gpa,college gpa,years to graduate
0,30,2094,some high school,62794,3.9,3.3,4
1,29,2022,some college,83775,3.9,3.3,4
2,27,2032,some college,75892,3.7,3.4,4
3,32,2218,associate's degree,84196,4.0,3.6,4
4,27,1958,some college,80541,3.6,3.5,4
...,...,...,...,...,...,...,...
995,29,2113,some high school,69339,3.8,3.7,3
996,26,1975,some high school,58990,3.5,3.5,3
997,31,2105,some college,38733,4.0,3.1,6
998,32,2160,high school,80222,4.0,3.6,5
999,31,2234,bachelor's degree,101782,4.0,3.7,4

Pierwszą rzeczą jaką zazwyczaj robimy z pozyskanym zbiorem danych jest jego podstawowa eksploracja przez sprawdzenie ile jakich wartości zostało wczytanych w jakich kolumnach. W kolejnych kilku przykładach będziemy eksplorować podstawowe statystyki kolumn i sprawdzać czy wszystko wczytało się prawidłowo. Następnie przejdziemy do tworzenia zestawień.

Podstawowe informacje o zbiorze danych - kontrolujemy poprawne wczytanie danych. Dla każdej kolumny podana jest liczba wartości w danej kolumnie (wyłączając braki w danych) oraz typ danych jako jaki zostały dane wczytane.

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ACT composite score          1000 non-null   int64
 1   SAT total score              1000 non-null   int64
 2   parental level of education  1000 non-null   str
 3   parental income              1000 non-null   int64
 4   high school gpa              1000 non-null   float64
 5   college gpa                  1000 non-null   float64
 6   years to graduate            1000 non-null   int64
dtypes: float64(2), int64(4), str(1)
memory usage: 54.8 KB

Wydobycie nazw kolumn - w postaci obiektu klasy  _Index_

In [61]:
df.columns

Index(['ACT composite score', 'SAT total score', 'parental level of education',
       'parental income', 'high school gpa', 'college gpa',
       'years to graduate'],
      dtype='str')

Opakujmy sobie to w serię danych dla przyjemniejszego przeglądania

In [62]:
pd.Series(df.columns)

0            ACT composite score
1                SAT total score
2    parental level of education
3                parental income
4                high school gpa
5                    college gpa
6              years to graduate
dtype: str


| Indeks | Nazwa kolumny | Wyjaśnienie |
| :---: | :--- | :--- |
| **0** | `ACT composite score` | **Wynik z egzaminu ACT** – amerykańskiego standaryzowanego testu wstępnego na studia, oceniającego wiedzę ze szkół średnich. |
| **1** | `SAT total score` | **Całkowity wynik z egzaminu SAT** – innego bardzo popularnego w USA testu wstępnego na uczelnie wyższe, składającego się głównie z sekcji matematycznej oraz językowej. |
| **2** | `parental level of education` | **Poziom wykształcenia rodziców** |
| **3** | `parental income` | **Dochód rodziców** – roczne zarobki rodziców |
| **4** | `high school gpa` | **Średnia ocen ze szkoły średniej** (w USA najczęściej w skali od 0.0 do 4.0) |
| **5** | `college gpa` | **Średnia ocen ze studiów** |
| **6** | `years to graduate` | **Liczba lat ile student potrzebował do ukończenia studiów** |

Wybór jednej kolumny

In [63]:
df["parental level of education"]

0        some high school
1            some college
2            some college
3      associate's degree
4            some college
              ...
995      some high school
996      some high school
997          some college
998           high school
999     bachelor's degree
Name: parental level of education, Length: 1000, dtype: str

Proste zestawienia tworzymy za pomocą metody `value_counts()`. Pozwala na poznanie rozkładu danych dyskretnych. Można podejrzeć czy nie ma pojedyńczych wartości w danych, które są nieprawidłowo wpisane. Domyślnie pomija wartości brakujące, jeśli występują.

In [64]:
df["parental level of education"].value_counts()

parental level of education
some college          223
some high school      208
high school           198
associate's degree    193
bachelor's degree     108
master's degree        70
Name: count, dtype: int64

In [65]:
df["parental level of education"].value_counts(dropna=False) # bez pomijania wartości brakujących

parental level of education
some college          223
some high school      208
high school           198
associate's degree    193
bachelor's degree     108
master's degree        70
Name: count, dtype: int64

W przypadku danych ciągłych (liczbowych) nie ma za wiele sensu, ponieważ nic ciekawego z tego nie możemy odczytać.

In [66]:
df["parental income"].value_counts()

parental income
33191     2
58020     2
74782     2
61201     2
74482     2
         ..
69339     1
58990     1
38733     1
80222     1
101782    1
Name: count, Length: 995, dtype: int64

Aby podglądać proste zależności między zmiennymi dyskretnymi oraz reprezentatywność podgrup możemy wykorzystać `pd.crosstab()`

In [67]:
pd.crosstab(df["parental level of education"], df["years to graduate"])

years to graduate            3   4   5   6   7   8   9   10
parental level of education
associate's degree           17  68  61  17  20   6   3   1
bachelor's degree            14  32  31  19   4   5   3   0
high school                  12  69  60  24  17  13   3   0
master's degree               9  19  25   7   7   1   2   0
some college                 27  84  56  36  13   6   1   0
some high school             16  51  75  30  19  14   3   0

`pd.crosstab()` przyjmuje jako dwa pierwsze parametry serie lub listy serii danych, pierwsza reprezentuje zmienne podsumowywane w wierszach a druga zmienne podsumowywane w kolumnach. Obydwa parametry muszą być tej samej długości lub tej samej liczby wierszy, ponieważ funkcja ta zestawia te dane ze sobą i zlicza poszczególne kombinacje wartości.

aby to zaprezentować dodajmy zmienną z zaokrągloną średnią do wartości 0.5.

In [68]:
df["rounded GPA"] = (df["high school gpa"]*2).round()/2
pd.crosstab([df["parental level of education"],df["rounded GPA"]], df["years to graduate"])

years to graduate                        3   4   5   6   7   8   9   10
parental level of education rounded GPA
associate's degree          3.0           1   1   0   0   0   1   0   0
                            3.5           7  25  18   6   5   3   0   0
                            4.0           9  42  43  11  15   2   3   1
bachelor's degree           3.0           1   0   1   0   0   0   0   0
                            3.5           2   7  11   4   2   1   2   0
                            4.0          11  25  19  15   2   4   1   0
high school                 2.5           0   0   1   0   0   0   0   0
                            3.0           1   7   5   2   6   0   0   0
                            3.5           7  34  30  11   9   8   1   0
                            4.0           4  28  24  11   2   5   2   0
master's degree             3.0           0   0   0   1   0   0   0   0
                            3.5           3   4   2   0   1   0   0   0
                            4.0           6  15  23   6   6   1   2   0
some college                3.0           2   2   3   4   1   0   0   0
                            3.5          12  35  28  10   5   2   0   0
                            4.0          13  47  25  22   7   4   1   0
some high school            2.5           0   0   0   2   0   0   0   0
                            3.0           1  10   6   6   4   3   2   0
                            3.5           8  26  48  13   8  10   1   0
                            4.0           7  15  21   9   7   1   0   0

In [69]:
pd.crosstab(df["years to graduate"], [df["parental level of education"],df["rounded GPA"]])

parental level of education associate's degree         bachelor's degree      \
rounded GPA                                3.0 3.5 4.0               3.0 3.5
years to graduate
3                                            1   7   9                 1   2
4                                            1  25  42                 0   7
5                                            0  18  43                 1  11
6                                            0   6  11                 0   4
7                                            0   5  15                 0   2
8                                            1   3   2                 0   1
9                                            0   0   3                 0   2
10                                           0   0   1                 0   0

parental level of education     high school             master's degree      \
rounded GPA                 4.0         2.5 3.0 3.5 4.0             3.0 3.5
years to graduate
3                            11           0   1   7   4               0   3
4                            25           0   7  34  28               0   4
5                            19           1   5  30  24               0   2
6                            15           0   2  11  11               1   0
7                             2           0   6   9   2               0   1
8                             4           0   0   8   5               0   0
9                             1           0   0   1   2               0   0
10                            0           0   0   0   0               0   0

parental level of education     some college         some high school          \
rounded GPA                 4.0          3.0 3.5 4.0              2.5 3.0 3.5
years to graduate
3                             6            2  12  13                0   1   8
4                            15            2  35  47                0  10  26
5                            23            3  28  25                0   6  48
6                             6            4  10  22                2   6  13
7                             6            1   5   7                0   4   8
8                             1            0   2   4                0   3  10
9                             2            0   0   1                0   2   1
10                            0            0   0   0                0   0   0

parental level of education
rounded GPA                 4.0
years to graduate
3                             7
4                            15
5                            21
6                             9
7                             7
8                             1
9                             0
10                            0

W powyższych przykładach możliwe było jedynie zliczanie wystąpień poszczególnych wartości lub kombinacji wartości. Często chcemy jednak poznać podsumowanie poszczególnych grup ze względu na zmienne (kolumny) zawarte w ramce danych.

Prosty przykład ze średnią oceną w szkole średniej dla studentów o rodzicach z różnym wykształceniem

In [70]:
df.groupby("parental level of education")["high school gpa"].mean()

parental level of education
associate's degree    3.798446
bachelor's degree     3.829630
high school           3.624242
master's degree       3.904286
some college          3.729148
some high school      3.540865
Name: high school gpa, dtype: float64

Średnie plasują się dość intuicyjnie. Dla tych co mają rodziców z lepszym wykształceniem średnia jest nieco wyższa. Jedank proszę pamiętać, że aby móc wnioskować na temat średnich różnych grup korzystamy z testów statystycznych (odsyłam do przedmiotu **Statystyka matematyczna**).

dugą opcją jest wykorzystanie metody `agg()` zamiast wprost metody funkcji agrefującej

In [71]:
df.groupby("parental level of education")["high school gpa"].agg("mean")

parental level of education
associate's degree    3.798446
bachelor's degree     3.829630
high school           3.624242
master's degree       3.904286
some college          3.729148
some high school      3.540865
Name: high school gpa, dtype: float64

zrealizujmy więc to co realizują metody `value_counts()` i `crosstab()`.

In [72]:
print(df.groupby("parental level of education")["high school gpa"].agg("count"))
print("\n")
# lista kolumn po których grupujemy!
print(df.groupby(["parental level of education","years to graduate"])["high school gpa"].agg("count"))

parental level of education
associate's degree    193
bachelor's degree     108
high school           198
master's degree        70
some college          223
some high school      208
Name: high school gpa, dtype: int64


parental level of education  years to graduate
associate's degree           3                    17
                             4                    68
                             5                    61
                             6                    17
                             7                    20
                             8                     6
                             9                     3
                             10                    1
bachelor's degree            3                    14
                             4                    32
                             5                    31
                             6                    19
                             7                     4
                             8                     5
                             9                     3
high school                  3                    12
                             4                    69
                             5                    60
                             6                    24
                             7                    17
                             8                    13
                             9                     3
master's degree              3                     9
                             4                    19
                             5                    25
                             6                     7
                             7                     7
                             8                     1
                             9                     2
some college                 3                    27
                             4                    84
                             5                    56
                             6                    36
                             7                    13
                             8                     6
                             9                     1
some high school             3                    16
                             4                    51
                             5                    75
                             6                    30
                             7                    19
                             8                    14
                             9                     3
Name: high school gpa, dtype: int64

Aby zrobić z tego tabelkę podobną do wyniku `crosstab()` należy utworzyć tabelę przestawną, będziemy taką wykonywać na następnych zajęciach.

Zammiast `count()` na kolumnie można wykonać metodę `size()` bez podawania kolumny

In [73]:
print(df.groupby(["parental level of education","years to graduate"]).size())

parental level of education  years to graduate
associate's degree           3                    17
                             4                    68
                             5                    61
                             6                    17
                             7                    20
                             8                     6
                             9                     3
                             10                    1
bachelor's degree            3                    14
                             4                    32
                             5                    31
                             6                    19
                             7                     4
                             8                     5
                             9                     3
high school                  3                    12
                             4                    69
                             5                    60
                             6                    24
                             7                    17
                             8                    13
                             9                     3
master's degree              3                     9
                             4                    19
                             5                    25
                             6                     7
                             7                     7
                             8                     1
                             9                     2
some college                 3                    27
                             4                    84
                             5                    56
                             6                    36
                             7                    13
                             8                     6
                             9                     1
some high school             3                    16
                             4                    51
                             5                    75
                             6                    30
                             7                    19
                             8                    14
                             9                     3
dtype: int64

Metoda `agg()` pozwala na policzenie więcej niż jednej statystyki.

Oprócz średniej policz jeszcze medianę i odchylenie standardowe. (więcej funkcji agregujących - vide Wykład)

In [74]:
df.groupby("parental level of education")["high school gpa"].agg(["mean","std","median"])

                                 mean       std  median
parental level of education
associate's degree           3.798446  0.242486     3.9
bachelor's degree            3.829630  0.215848     3.9
high school                  3.624242  0.288736     3.6
master's degree              3.904286  0.160105     4.0
some college                 3.729148  0.257680     3.8
some high school             3.540865  0.306473     3.6

A jak sobie radzą studenci na studiach biorąc pod uwagę wykształcenie ich rodziców i ich średnią ze szkoły średniej? (wykorzystajmy zaokrąglone średnie ze szkoły średniej)

In [75]:
df.groupby(["parental level of education","rounded GPA"])["college gpa"].agg(["mean","std"])

                                             mean       std
parental level of education rounded GPA
associate's degree          3.0          3.233333  0.208167
                            3.5          3.342188  0.211424
                            4.0          3.474603  0.201171
bachelor's degree           3.0          3.200000  0.282843
                            3.5          3.272414  0.198020
                            4.0          3.493506  0.226145
high school                 2.5          2.800000       NaN
                            3.0          3.280952  0.136452
                            3.5          3.301000  0.183949
                            4.0          3.456579  0.196866
master's degree             3.0          2.800000       NaN
                            3.5          3.460000  0.150555
                            4.0          3.545763  0.206216
some college                3.0          3.266667  0.201509
                            3.5          3.285870  0.210484
                            4.0          3.447059  0.205362
some high school            2.5          2.800000  0.141421
                            3.0          3.090625  0.202181
                            3.5          3.256140  0.185317
                            4.0          3.375000  0.234792

Jak widzimy w niektórych przypadkach było za mało danych aby policzyć odchylenie standardowe (potrzeba co najmniej dwóch wierszy w danej kombinacji wartości zmiennych grupujących). W takich przypadkach jest zwracana wartość reprezentująca brak danych a w tabeli widzimy to jako _NaN_ - _not a number_.

Funkcje agregujące dostępne domyślnie z biblioteką często są niewystarczające. Dlatego można wykorzystać funkcje lambda do definiowania swoich złożonych funkcji agregujących.

In [76]:
df.groupby("parental level of education")["high school gpa"].agg(lambda x: max(x)-min(x))

parental level of education
associate's degree    1.2
bachelor's degree     0.8
high school           1.3
master's degree       0.8
some college          1.1
some high school      1.6
Name: high school gpa, dtype: float64

Trzecia największa średnia dla studentów o tym samym poziomie wykształcenia rodziców

In [77]:

df.groupby("parental level of education")["high school gpa"].agg(lambda x: x.nlargest(3).iloc[-1])

parental level of education
associate's degree    4.0
bachelor's degree     4.0
high school           4.0
master's degree       4.0
some college          4.0
some high school      4.0
Name: high school gpa, dtype: float64

## Zadania samodzielne

Dla danych pacjentów umieszczonych w pliku _heart_disease.csv_ wykonaj poniższe polecenia.

In [78]:
df = pd.read_csv("heart_disease.csv")
df

,Gender,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,Heart_ stroke
0,Male,39,postgraduate,0,0.0,0.0,no,0,0,195.0,106.0,70.0,26.97,80.0,77.0,No
1,Female,46,primaryschool,0,0.0,0.0,no,0,0,250.0,121.0,81.0,28.73,95.0,76.0,No
2,Male,48,uneducated,1,20.0,0.0,no,0,0,245.0,127.5,80.0,25.34,75.0,70.0,No
3,Female,61,graduate,1,30.0,0.0,no,1,0,225.0,150.0,95.0,28.58,65.0,103.0,yes
4,Female,46,graduate,1,23.0,0.0,no,0,0,285.0,130.0,84.0,23.10,85.0,85.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,Male,50,uneducated,1,1.0,0.0,no,1,0,313.0,179.0,92.0,25.97,66.0,86.0,yes
4234,Male,51,graduate,1,43.0,0.0,no,0,0,207.0,126.5,80.0,19.71,65.0,68.0,No
4235,Female,48,primaryschool,1,20.0,NaN,no,0,0,248.0,131.0,72.0,22.00,84.0,86.0,No
4236,Female,44,uneducated,1,15.0,0.0,no,0,0,210.0,126.5,87.0,19.16,86.0,NaN,No
4237,Female,52,primaryschool,0,0.0,0.0,no,0,0,269.0,133.5,83.0,21.47,80.0,107.0,No

Co oznaczają poszczególne kolumny
| Nazwa kolumny | objaśnienie |
|---:|:---|
|            Gender | płeć |
|               age | wiek |
|         education | poziom wykształcenia |
|     currentSmoker | czy obecnie pali? |
|        cigsPerDay | ile papierosów wypala dziennie? |
|            BPMeds | Leki na ciśnienie krwi |
|   prevalentStroke | czy przeszedł udar |
|      prevalentHyp | występowanie nadciśnienia |
|          diabetes | cukrzyca |
|           totChol | poziom całego cholesterolu |
|             sysBP | "ciśnienie górne" |
|             diaBP | "ciśnienie dolne" |
|               BMI | wskaźnik wagi/wzrostu |
|         heartRate | tętno - "uderzenia" serca na minutę |
|           glucose | poziom glukozy we krwii |
|     Heart_ stroke | czy wystąpił zawał serca |

Treść zadań

Za pomocą jednego polecenia

1. Sprawdź ilu pacjentów ma wykształcenie na jakim poziomie za pomocą dwóch metod pokazanych wyżej w notatniku.
1. Sprawdź ile jest osób palących
1. Ile jest osób palących wśród odpowiednio kobiet i mężczyzn (również dwoma metodami)?
1. Sprawdź ilu pacjentów ma wykształcenie na jakim poziomie wśród odpowiednio kobiet i mężczyzn.
1. Sprawdź jaki jest średni wiek odpowiednio kobiet i mężczyzn?
1. Sprawdź jaka jest mediana wieku odpowiednio kobiet i mężczyzn?
1. Dla poszczególnych płci sprawdź jaki jest średni wiek, wskaźnik BMI, tętno.
1. Ile papierosów wypalają średino mężczyźni i kobiety w zależności od tego poziomu wykształcenia.
1. Podaj średnie ciśnienie "wysokie" i "niskie" dla kobiet i mężczyzn w zależności od poziomu wykształcenia.
1. Dla wszystkich poziomów wykształcenia podaj różnicę między najwyższym a najniższym wskaźnikiem BMI (funkcja lambda).

In [79]:
# 1.1 Sprawdź ilu pacjentów ma wykształcenie na jakim poziomie za pomocą dwóch metod pokazanych wyżej w notatniku.

df["education"].value_counts()

education
uneducated       1720
primaryschool    1253
graduate          687
postgraduate      473
Name: count, dtype: int64

In [80]:
# 1.2 Sprawdź ilu pacjentów ma wykształcenie na jakim poziomie za pomocą dwóch metod pokazanych wyżej w notatniku.

df["education"].value_counts(dropna=False)

education
uneducated       1720
primaryschool    1253
graduate          687
postgraduate      473
NaN               105
Name: count, dtype: int64

In [81]:
# 2. Sprawdź ile jest osób palących
df["currentSmoker"].value_counts(dropna=False)

currentSmoker
0    2144
1    2094
Name: count, dtype: int64

In [82]:
# 3.1 Ile jest osób palących wśród odpowiednio kobiet i mężczyzn (również dwoma metodami)?

pd.crosstab(df["Gender"], df["currentSmoker"])

currentSmoker     0     1
Gender
Female         1431   988
Male            713  1106

In [91]:
# 3.2 Ile jest osób palących wśród odpowiednio kobiet i mężczyzn (również dwoma metodami)?

df.groupby(["Gender","currentSmoker"]).size()

Gender  currentSmoker
Female  0                1431
        1                 988
Male    0                 713
        1                1106
dtype: int64

In [84]:
# 4. Sprawdź ilu pacjentów ma wykształcenie na jakim poziomie wśród odpowiednio kobiet i mężczyzn.

# df.groupby(["education", "Gender"]).size()
pd.crosstab(df["education"], df["Gender"])

Gender         Female  Male
education
graduate          463   224
postgraduate      197   276
primaryschool     764   489
uneducated        943   777

In [85]:
# 5. Sprawdź jaki jest średni wiek odpowiednio kobiet i mężczyzn?

df.groupby("Gender")["age"].agg("mean")

Gender
Female    49.800331
Male      49.298516
Name: age, dtype: float64

In [86]:
# 6. Sprawdź jaka jest mediana wieku odpowiednio kobiet i mężczyzn?

df.groupby("Gender")["age"].agg("median")

Gender
Female    49.0
Male      48.0
Name: age, dtype: float64

In [87]:
# 7. Dla poszczególnych płci sprawdź jaki jest średni wiek, wskaźnik BMI, tętno.

df.groupby("Gender")[["age", "BMI", "heartRate"]].agg("mean")

              age        BMI  heartRate
Gender
Female  49.800331  25.512636  77.094667
Male    49.298516  26.185656  74.261276

In [88]:
# 8. Ile papierosów wypalają średino mężczyźni i kobiety w zależności od tego poziomu wykształcenia.

df.groupby(["education", "Gender"])["cigsPerDay"].agg("mean")

education      Gender
graduate       Female     5.715835
               Male      13.045249
postgraduate   Female     5.591837
               Male      12.313869
primaryschool  Female     7.025033
               Male      14.243299
uneducated     Female     4.679829
               Male      13.536869
Name: cigsPerDay, dtype: float64

In [89]:
# 9. Podaj średnie ciśnienie "wysokie" i "niskie" dla kobiet i mężczyzn w zależności od poziomu wykształcenia.

df.groupby(["education", "Gender"])[["sysBP", "diaBP"]].agg("mean")

                           sysBP      diaBP
education     Gender
graduate      Female  128.143629  80.637149
              Male    131.939732  84.008929
postgraduate  Female  127.657360  80.781726
              Male    128.445652  83.286232
primaryschool Female  132.023560  81.755890
              Male    128.960123  83.214724
uneducated    Female  137.461294  83.860551
              Male    133.893179  83.942085

In [90]:
# 10. Dla wszystkich poziomów wykształcenia podaj różnicę między najwyższym a najniższym wskaźnikiem BMI (funkcja lambda).

df.groupby("education")["BMI"].agg(lambda x: max(x)-min(x))

education
graduate         22.87
postgraduate     23.99
primaryschool    29.83
uneducated       41.26
Name: BMI, dtype: float64